version: '3.8'
networks:
  mysql_net:
    external: true
services:
  tomcat:
    image: tomcat
    container_name: movie
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - nginx
    networks:
      - mysql_net
    volumes:
      - ./package:/usr/local/tomcat/webapps
      - /Users/mjj/img:/usr/img
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: movie
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    networks:
      - mysql_net
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - /Users/mjj/img:/usr/img
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
